class UiIntent:
    LIST_OPEN_SELECTED = "list.open_selected"
    NEW_PLAN = "plan.new"
    OPEN_SETTINGS = "settings.open"
    DELETE_DESK = "desk.delete"
    SET_TEACHER_DESK = "desk.set_teacher"
    ADD_SYMBOL = "desk.add_symbol"
    ESCAPE = "selection.clear"
    CONFIRM_SELECTION = "selection.confirm"
    MOVE_UP = "selection.up"
    MOVE_DOWN = "selection.down"
    MOVE_LEFT = "selection.left"
    MOVE_RIGHT = "selection.right"
    ZOOM_IN = "viewport.zoom_in"
    ZOOM_OUT = "viewport.zoom_out"
    GO_TO_LIST = "view.list"
    TOGGLE_THEME = "theme.toggle"
